export const ar = {
  appName: "تاووس",
  appTagline: "خدمات الحلاقة عند الطلب",
  heroLine1: "ابدُ بمظهر رائع.",
  heroLine2: "احجز كالمحترفين.",
  appVersion: "تاووس الإصدار 1.0 · ابدُ بمظهر رائع.",
  back: "رجوع",
  continue: "متابعة",
  cancel: "إلغاء",
  ok: "حسناً",
  error: "خطأ",
  notSet: "غير محدد",
  mad: "درهم",
  whoAreYou: "من أنت؟",
  chooseRole: "اختر كيف تريد استخدام تاووس",
  alreadyHaveAccount: "هل لديك حساب بالفعل؟",
  signIn: "تسجيل الدخول",
  roleClient: "عميل",
  roleClientSub: "احجز خدمات الحلاقة بسعرك",
  roleSalon: "صاحب صالون",
  roleSalonSub: "سجّل محلّك وأدر الكراسي",
  rolePro: "حلاق محترف",
  roleProSub: "اختر خدماتك واستلم طلبات",
  createAccount: "إنشاء حسابك",
  quickSetup: "إعداد سريع — 3 حقول فقط",
  fullName: "الاسم الكامل",
  fullNamePlaceholder: "أحمد بنعلي",
  gmailAddress: "بريد Gmail",
  gmailPlaceholder: "you@gmail.com",
  phoneNumber: "رقم الهاتف",
  phonePlaceholder: "0612 345 678",
  alreadyRegistered: "هل أنت مسجّل بالفعل؟",
  welcomeBack: "مرحباً بعودتك",
  enterPhone: "أدخل رقم هاتفك للمتابعة",
  newHere: "جديد هنا؟",
  createAccountLink: "إنشاء حساب ←",
  phoneNotFound: "الهاتف غير موجود. أنشئ حساباً أولاً.",
  serviceHaircut: "قص الشعر",
  serviceBeard: "تهذيب اللحية",
  serviceNails: "العناية بالأظافر",
  serviceFull: "الباقة الكاملة",
  statusOpen: "مفتوح",
  statusInProgress: "جارٍ",
  statusCompleted: "مكتمل",
  statusCancelled: "ملغى",
  statusPending: "معلّق",
  statusAccepted: "مقبول",
  statusRejected: "مرفوض",
  statusClaimed: "محجوز",
  statusNoshow: "غائب",
  goodMorning: "صباح الخير",
  goodAfternoon: "مساء الخير",
  goodEvening: "مساء النور",
  activeJobs: "وظائف نشطة",
  pendingBids: "عروض معلّقة",
  totalJobs: "إجمالي الوظائف",
  postNewJob: "نشر وظيفة جديدة",
  recentJobs: "الوظائف الأخيرة",
  noJobsYet: "لا وظائف بعد — انشر أولى وظائفك!",
  nearbyRequests: "الطلبات القريبة",
  live: "مباشر",
  noRequestsYet: "لا طلبات بعد",
  clientsPosting: "العملاء ينشرون — تحقق مجدداً قريباً",
  beTheFirst: "⚡ كن الأول!",
  openRequestsLabel: (n: number) =>
    `${n} طلب${n === 1 ? "" : "ات"} مفتوح${n === 1 ? "" : "ة"}`,
  bidsCount: (n: number) => `${n} عرض`,
  salonDashboard: "لوحة تحكم الصالون",
  goLive: "بث مباشر",
  youAreLive: "🟢 أنت الآن مباشر",
  clientsCanFind: "يمكن للعملاء إيجادك وحجزك",
  startAccepting: "ابدأ قبول الحجوزات المباشرة",
  earnedToday: "درهم مكتسب اليوم",
  liveQueueTitle: (n: number) => `الطابور المباشر (${n})`,
  noClaimsYet: "لا حجوزات بعد — شارك رابطك!",
  goLiveToStart: "ابدأ البث لقبول الحجوزات",
  topProfessionals: "أفضل المحترفين",
  noProfessionals: "لا محترفين بعد",
  allRequests: "جميع الطلبات",
  noRequests: "لا طلبات الآن",
  analytics: "التحليلات",
  analyticsComingSoon: "التحليلات التفصيلية قريباً",
  yourEarningsHere: "أرباحك وأنشطتك ستظهر هنا",
  todayRevenue: "إيرادات اليوم",
  thisWeek: "هذا الأسبوع",
  chairsBusy: "كراسي مشغولة",
  avgRating: "متوسط التقييم",
  jobs: "وظائف",
  jobsCount: (n: number) => `${n} وظيفة`,
  myJobs: "وظائفي",
  postFirstJob: "انشر أول وظيفة لك",
  cancelThisJob: "إلغاء هذه الوظيفة",
  cancelJobTitle: "إلغاء الوظيفة؟",
  cancelJobMsg: "لا يمكن التراجع عن هذا.",
  keepJob: "احتفظ بها",
  cancelJobConfirm: "إلغاء",
  couldNotCancel: "تعذّر الإلغاء",
  noBidsOnJob: "لا وظائف بعد",
  myBids: "عروضي",
  availableJobs: (n: number) => `⚡ وظائف متاحة (${n})`,
  noBidsYet: "لا عروض بعد",
  browseToBid: "تصفح الوظائف أعلاه وضع عرضك الأول",
  yourBid: "عرضك",
  budget: "الميزانية",
  jobNum: (n: number) => `وظيفة #${n}`,
  couldNotBid: "تعذّر تقديم العرض",
  chairQueueTitle: (n: number) => `طابور الكراسي (${n})`,
  queueEmpty: "الطابور فارغ",
  goLiveForQueue: "ابدأ البث من لوحة التحكم لقبول الحجوزات",
  chair: "كرسي",
  depositLabel: "مبلغ الحجز",
  clientNum: (n: number) => `عميل #${n}`,
  postJobTitle: "نشر وظيفة",
  setYourPrice: "حدد سعرك — سيقدم المحترفون عروضهم",
  serviceLabel: "الخدمة",
  budgetLabel: "ميزانيتك (درهم)",
  locationLabel: "موقعك",
  locationPlaceholder: "12 شارع أم الربيع، الدار البيضاء",
  postJobBtn: "نشر الوظيفة",
  jobPosted: "تم نشر الوظيفة!",
  biddingStart: "سيبدأ المحترفون في تقديم عروضهم قريباً.",
  couldNotPost: "تعذّر نشر الوظيفة",
  email: "البريد الإلكتروني",
  phone: "الهاتف",
  location: "الموقع",
  account: "الحساب",
  editProfile: "تعديل الملف الشخصي",
  verifiedPro: "محترف موثّق",
  helpSupport: "المساعدة والدعم",
  signOut: "تسجيل الخروج",
  signOutTitle: "تسجيل الخروج؟",
  signOutMsg: "ستحتاج إلى تسجيل الدخول مجدداً.",
  language: "اللغة",
  roleClientLabel: "عميل",
  roleProLabel: "حلاق محترف",
  roleSalonLabel: "صاحب صالون",
  tabHome: "الرئيسية",
  tabDashboard: "لوحة التحكم",
  tabExplore: "استكشاف",
  tabRequests: "الطلبات",
  tabMyJobs: "وظائفي",
  tabMyBids: "عروضي",
  tabQueue: "الطابور",
  tabPostJob: "نشر وظيفة",
  tabProfile: "الملف الشخصي",
  tabFavorites: "المفضلة",
  favoritesTitle: "صالوناتي المفضلة",
  addedToFavorites: "تمت الإضافة إلى المفضلة!",
  removedFromFavorites: "تمت الإزالة من المفضلة",
  noFavorites: "لا صالونات مفضلة بعد",
  noFavoritesSub: "اضغط ❤️ على أي صالون لإضافته",
  browseSalons: "تصفح الصالونات",
  bookNow: "احجز الآن",
  viewMap: "الخريطة",
  remove: "إزالة",
  filterAll: "الكل",
  filterMens: "حلاقة رجالية",
  filterWomens: "صالون نسائي",
  filterNearMe: "قريب مني",
  filterAvailNow: "متاح الآن",
  chairsAvailable: (n: number) => `${n} كرسي متاح`,
  searchSalons: "ابحث بالاسم أو المدينة...",
  salonsNearby: "الصالونات القريبة",
  salonCategory: "فئة الصالون",
  waitTime: "وقت الانتظار",
  minutes: (n: number) => `${n} دقيقة`,
};

export const en = {
  appName: "TAWOSS",
  appTagline: "ON-DEMAND GROOMING",
  heroLine1: "Look fresh.",
  heroLine2: "Book like a boss.",
  appVersion: "Tawoss v1.0 · Look fresh. Book like a boss.",
  back: "Back",
  continue: "Continue",
  cancel: "Cancel",
  ok: "OK",
  error: "Error",
  notSet: "Not set",
  mad: "MAD",
  whoAreYou: "Who are you?",
  chooseRole: "Choose how you want to use Tawoss",
  alreadyHaveAccount: "Already have an account?",
  signIn: "Sign In",
  roleClient: "Customer",
  roleClientSub: "Book grooming services at your price",
  roleSalon: "Salon Owner",
  roleSalonSub: "Register your shop & manage chairs",
  rolePro: "Freelancer / Pro",
  roleProSub: "Choose your services & take jobs",
  createAccount: "Create your account",
  quickSetup: "Quick setup — just 3 fields",
  fullName: "Full Name",
  fullNamePlaceholder: "Ahmed Benali",
  gmailAddress: "Gmail Address",
  gmailPlaceholder: "you@gmail.com",
  phoneNumber: "Phone Number",
  phonePlaceholder: "0612 345 678",
  alreadyRegistered: "Already registered?",
  welcomeBack: "Welcome back",
  enterPhone: "Enter your phone number to continue",
  newHere: "New here?",
  createAccountLink: "Create account →",
  phoneNotFound: "Phone not found. Create an account first.",
  serviceHaircut: "Haircut",
  serviceBeard: "Beard Trim",
  serviceNails: "Nails",
  serviceFull: "Full Package",
  statusOpen: "Open",
  statusInProgress: "In Progress",
  statusCompleted: "Completed",
  statusCancelled: "Cancelled",
  statusPending: "Pending",
  statusAccepted: "Accepted",
  statusRejected: "Rejected",
  statusClaimed: "Claimed",
  statusNoshow: "No-Show",
  goodMorning: "Good morning",
  goodAfternoon: "Good afternoon",
  goodEvening: "Good evening",
  activeJobs: "Active Jobs",
  pendingBids: "Pending Bids",
  totalJobs: "Total Jobs",
  postNewJob: "Post a New Job",
  recentJobs: "Recent Jobs",
  noJobsYet: "No jobs yet — post your first one!",
  nearbyRequests: "Nearby Requests",
  live: "LIVE",
  noRequestsYet: "No requests yet",
  clientsPosting: "Clients are posting — check back soon",
  beTheFirst: "⚡ Be the first!",
  openRequestsLabel: (n: number) => `${n} open request${n === 1 ? "" : "s"}`,
  bidsCount: (n: number) => `${n} bid${n === 1 ? "" : "s"}`,
  salonDashboard: "Salon Dashboard",
  goLive: "Go Live",
  youAreLive: "🟢 You're LIVE",
  clientsCanFind: "Clients can find & book you",
  startAccepting: "Start accepting walk-ins",
  earnedToday: "MAD earned today",
  liveQueueTitle: (n: number) => `Live Queue (${n})`,
  noClaimsYet: "No claims yet — share your link!",
  goLiveToStart: "Go live to start accepting walk-ins",
  topProfessionals: "Top Professionals",
  noProfessionals: "No professionals yet",
  allRequests: "All Requests",
  noRequests: "No requests right now",
  analytics: "Analytics",
  analyticsComingSoon: "Detailed analytics coming soon",
  yourEarningsHere: "Your earnings & activity will appear here",
  todayRevenue: "Today's Revenue",
  thisWeek: "This Week",
  chairsBusy: "Chairs Busy",
  avgRating: "Avg Rating",
  jobs: "jobs",
  jobsCount: (n: number) => `${n} job${n === 1 ? "" : "s"}`,
  myJobs: "My Jobs",
  postFirstJob: "Post your first job",
  cancelThisJob: "Cancel this job",
  cancelJobTitle: "Cancel job?",
  cancelJobMsg: "This cannot be undone.",
  keepJob: "Keep it",
  cancelJobConfirm: "Cancel Job",
  couldNotCancel: "Could not cancel",
  noBidsOnJob: "No jobs yet",
  myBids: "My Bids",
  availableJobs: (n: number) => `⚡ Available Jobs (${n})`,
  noBidsYet: "No bids yet",
  browseToBid: "Browse jobs above and place your first bid",
  yourBid: "Your bid",
  budget: "Budget",
  jobNum: (n: number) => `Job #${n}`,
  couldNotBid: "Could not place bid",
  chairQueueTitle: (n: number) => `Chair Queue (${n})`,
  queueEmpty: "Queue is empty",
  goLiveForQueue: "Go live on the Dashboard to start accepting walk-ins",
  chair: "Chair",
  depositLabel: "Deposit",
  clientNum: (n: number) => `Client #${n}`,
  postJobTitle: "Post a Job",
  setYourPrice: "Set your price — pros will bid for it",
  serviceLabel: "SERVICE",
  budgetLabel: "YOUR BUDGET (MAD)",
  locationLabel: "YOUR LOCATION",
  locationPlaceholder: "12 Rue Oum Errabie, Casablanca",
  postJobBtn: "Post Job",
  jobPosted: "Job posted!",
  biddingStart: "Professionals will start bidding shortly.",
  couldNotPost: "Could not post job",
  email: "Email",
  phone: "Phone",
  location: "Location",
  account: "ACCOUNT",
  editProfile: "Edit Profile",
  verifiedPro: "Verified Professional",
  helpSupport: "Help & Support",
  signOut: "Sign Out",
  signOutTitle: "Sign out?",
  signOutMsg: "You'll need to sign in again.",
  language: "Language",
  roleClientLabel: "Customer",
  roleProLabel: "Freelancer / Pro",
  roleSalonLabel: "Salon Owner",
  tabHome: "Home",
  tabDashboard: "Dashboard",
  tabExplore: "Explore",
  tabRequests: "Requests",
  tabMyJobs: "My Jobs",
  tabMyBids: "My Bids",
  tabQueue: "Queue",
  tabPostJob: "Post Job",
  tabProfile: "Profile",
  tabFavorites: "Favorites",
  favoritesTitle: "My Favorite Salons",
  addedToFavorites: "Added to favorites!",
  removedFromFavorites: "Removed from favorites",
  noFavorites: "No favorite salons yet",
  noFavoritesSub: "Tap ❤️ on any salon to add it here",
  browseSalons: "Browse Salons",
  bookNow: "Book Now",
  viewMap: "Map",
  remove: "Remove",
  filterAll: "All",
  filterMens: "Men's",
  filterWomens: "Women's",
  filterNearMe: "Near Me",
  filterAvailNow: "Available",
  chairsAvailable: (n: number) => `${n} chair${n === 1 ? "" : "s"} free`,
  searchSalons: "Search by name or city...",
  salonsNearby: "Nearby Salons",
  salonCategory: "Category",
  waitTime: "Wait time",
  minutes: (n: number) => `${n} min`,
};

export const SVC_LABEL_AR = (t: typeof ar | typeof en) => ({
  haircut: t.serviceHaircut,
  beard: t.serviceBeard,
  nails: t.serviceNails,
  full_grooming: t.serviceFull,
});

export const STATUS_LABEL = (t: typeof ar | typeof en) => ({
  open: t.statusOpen,
  in_progress: t.statusInProgress,
  completed: t.statusCompleted,
  cancelled: t.statusCancelled,
  pending: t.statusPending,
  accepted: t.statusAccepted,
  rejected: t.statusRejected,
  claimed: t.statusClaimed,
  noshow: t.statusNoshow,
});
